Makefile, README.md
`make all` to start all the project
Better README documentation on how to set up the project on any device.
=> Better documentation & more make commands

client/components/Unit.tsx, client/components/UserDetails.tsx
Elements are now alot more accessible, much shorter scrolling and better looking.
close #5
=> [feature] Whole better UX

CHANGELOG.md
=> [doc] CHANGELOG.md file

client/components/UserDetails.tsx, imports/api/ADMethod.ts, server/main.ts, settings-mock.json
`ADMethod` is calling 5 EPFL AD's servers.
close #6
=> [feature] AD Data

client/components/Search.tsx, client/components/Virtualize.tsx, client/home.tsx
`/:data` can autocomplete the input and the userDetails so links can be shared between people.
close #20
=> [feature] Shareable links

client/home.tsx
=> [feature] Sticky footer

client/components/CheckLDAP.tsx, imports/api/checkLDAPMethod.ts
The checkLDAP route is now a 1:1 from idp-exop
=> [refactor] Complete `/checkLDAP`

client/components/UserDetails.tsx
Using a really big link, some JS and alot of query strings, we can now create a ticket for user directly from ATARI.
=> [feature] Create a ticket for user button

client/components/Unit.tsx, imports/types/UnitInfos.ts, server/cadidb/userDetails.ts
When expanding accreditation of someone, we can now see the Admins IT of the person.
Admins IT are expanded by default if there is less than 10. If there are more than 10 Admins IT, it should be manually expanded.
close #30
=> [feature] AdminsIT

client/components/Search.tsx, client/components/SearchBar.tsx, client/components/UserDetails.tsx, imports/api/DigestUser.ts, imports/api/apiMethod.ts, server/main.ts, settings-mock.json
New autocomplete using api.epfl.ch
Settings to authenticate the API
Updated DigestUser to match the response of api.epfl.ch (but still subject to change)
Autocomplete is still a bit messy, subject to change
close #24
close #29
=> [feature] Search using api.epfl.ch

client/components/CheckAD.tsx, client/components/UserDetails.tsx, client/home.tsx, imports/api/ADMethod.ts
CheckAD is now a specific route from ATARI.
Not usins windows.epfl.ch anymore.
close #47
=> [feature] CheckAD is now ours

client/components/UserDetails.tsx
=> [fix] Wrong date when never connected

client/components/SearchBar.tsx
=> [feature] Loading spinner in search bar

imports/api/apiMethod.ts
This was causing the problem that typing accented characters didn't work.
close #88
=> [fix] EncodeURI for api URLs

client/components/CheckInv.tsx, client/home.tsx
=> [feature] `/inv/:invNumber`

client/components/UserDetails.tsx
=> [fix] link to People

client/components/UserDetails.tsx, imports/api/apiMethod.ts
Adding a boolean if user has the property to have an e-mail address or not.
close #100
=> [feature] Own email adress property

client/components/UserDetails.tsx
Thanks to @mfblanch for enlightening me about `mycamipro.epfl.ch/admin`, there is now a link to the camipro admin page with a queryString to search for the user's sciper
close #95
=> [feature] Added tool to camipro admin page

client/components/UserDetails.tsx, imports/api/DigestUser.ts, imports/api/apiMethod.ts
=> [feature] Added SAP registration number

client/components/Unit.tsx
Also, with the `herited` notion.
The user can have IT admins who are not from his unit.
close #106
=> [feature] AdminsIT with unit

client/components/UserDetails.tsx
If user has many phone numbers, only displaying two.
#78
=> [feature] Phone number
